apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginxsvc-deployment
  labels:
    app: my-app2
  namespace: lesson3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app2
  template:
    metadata:
      labels:
        app: my-app2
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
      initContainers:
       - name: init-my-service
         image: busybox
         command: ['sh', '-c', 'until nslookup my-service2.lesson3.svc.cluster.local; do echo waiting for my-service2; sleep 2; done;']
