apiVersion: v1
kind: Service
metadata:
  name: my-service2
  namespace: lesson3
spec:
  ports:
    - name: test-nginx
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: my-app2
