apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-test-deployment
  labels:
    app: my-app1
  namespace: lesson3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app1
  template:
    metadata:
      labels:
        app: my-app1
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
#        ports:
#        - containerPort: 80
      - name: multitool
        image: wbitt/network-multitool
        env:
        - name: HTTP_PORT
          value: "8080"
#        ports:
#        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: test-service
  namespace: lesson3
spec:
  ports:
    - name: test-nginx
      port: 80
      protocol: TCP
      targetPort: 80
    - name: test-multitool
      port: 8088
      protocol: TCP
      targetPort: 8080
  selector:
    app: my-app1
