apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: my-pod-reader
  namespace: lesson2-4
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-pod-reader-bind
  namespace: lesson2-4
subjects:
  - kind: User
    name: semen
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: my-pod-reader
  apiGroup: rbac.authorization.k8s.io