apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-test4-deployment
  labels:
    app: my-app4
  namespace: lesson4
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app4
  template:
    metadata:
      labels:
        app: my-app4
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
      - name: multitool
        image: wbitt/network-multitool
        env:
        - name: HTTP_PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: test4-service
  namespace: lesson4
spec:
  ports:
    - name: port-nginx
      port: 9001
      protocol: TCP
      targetPort: 80
    - name: port-multitool
      port: 9002
      protocol: TCP
      targetPort: 8080
  selector:
    app: my-app4
