apiVersion: v1
kind: Pod
metadata:
  labels:
    app: beatlapp
  name: hello-world
  namespace: default
spec:
  containers:
  - image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
    imagePullPolicy: IfNotPresent
    name: echoserver
    env:
    - name: HTTP_PORT
      value: "8080"